@WebApiEngine_HostAddress = http://localhost:5182
@ProcessId = Process_02kj6io

### Get all deployed ProcessDefinitions
GET {{WebApiEngine_HostAddress}}/process/
Accept: application/json

### Starts a new process instance
POST {{WebApiEngine_HostAddress}}/process/{{ProcessId}}
Accept: application/json
