/**
 * Deutsche Beschriftung fuer dmn-js.
 *
 * dmn-js schreibt jeden sichtbaren Text ueber seinen `translate`-Dienst. Die Konsole ist
 * durchgaengig deutsch; eine englische Tabelle mitten darin wirkte wie ein Fremdkoerper.
 * Nicht erfasste Texte bleiben englisch statt zu verschwinden - ein neuer Text in einer
 * spaeteren dmn-js-Fassung faellt so auf, bricht aber nichts.
 *
 * Platzhalter wie `{kind}` ersetzt dmn-js nicht selbst; das uebernimmt `translate` hier.
 */
const GERMAN: Record<string, string> = {
  '"value"': '"Wert"',
  '"value", "value", ...': '"Wert", "Wert", …',
  'Activate hand tool': 'Hand-Werkzeug',
  'Activate lasso tool': 'Lasso-Werkzeug',
  'Add cell description': 'Beschreibung hinzufügen',
  'Add input': 'Eingabe hinzufügen',
  'Add input column left': 'Eingabespalte links einfügen',
  'Add input column right': 'Eingabespalte rechts einfügen',
  'Add output': 'Ergebnis hinzufügen',
  'Add output column left': 'Ergebnisspalte links einfügen',
  'Add output column right': 'Ergebnisspalte rechts einfügen',
  'Add parameter': 'Parameter hinzufügen',
  'Add predefined values': 'Vorgegebene Werte hinzufügen',
  'Add rule': 'Regel hinzufügen',
  'Add rule above': 'Regel darüber einfügen',
  'Add rule below': 'Regel darunter einfügen',
  'Add text annotation': 'Anmerkung hinzufügen',
  'Add values': 'Werte hinzufügen',
  After: 'Nach',
  And: 'und',
  Annotation: 'Anmerkung',
  Annotations: 'Anmerkungen',
  'Append business knowledge model': 'Wissensmodell anhängen',
  'Append decision': 'Entscheidung anhängen',
  'Append input data': 'Eingabedaten anhängen',
  'Append knowledge source': 'Wissensquelle anhängen',
  Before: 'Vor',
  Between: 'Zwischen',
  'Boolean value': 'Wahrheitswert',
  'Change cell expression language': 'Ausdruckssprache der Zelle ändern',
  'Change type': 'Art ändern',
  'Clear predefined values': 'Vorgegebene Werte entfernen',
  Comparison: 'Vergleich',
  'Comparison operator': 'Vergleichsoperator',
  'Connect to other element': 'Mit anderem Element verbinden',
  'Copy input column': 'Eingabespalte kopieren',
  'Copy output column': 'Ergebnisspalte kopieren',
  'Copy rule': 'Regel kopieren',
  'Create decision': 'Entscheidung anlegen',
  'Create input data': 'Eingabedaten anlegen',
  'Create knowledge model': 'Wissensmodell anlegen',
  'Create knowledge source': 'Wissensquelle anlegen',
  'Custom values': 'Eigene Werte',
  'Cut input column': 'Eingabespalte ausschneiden',
  'Cut output column': 'Ergebnisspalte ausschneiden',
  'Cut rule': 'Regel ausschneiden',
  Date: 'Datum',
  'Date and time': 'Datum und Uhrzeit',
  'Date and time value': 'Datums- und Zeitwert',
  'Date value': 'Datumswert',
  'Decision name': 'Name der Entscheidung',
  'Decision name: ': 'Name der Entscheidung: ',
  'Definition ID': 'Kennung der Definition',
  'Definition name': 'Name der Definition',
  Delete: 'Löschen',
  'Duration value': 'Dauer',
  Edit: 'Bearbeiten',
  'Edit boolean': 'Wahrheitswert bearbeiten',
  'Edit date': 'Datum bearbeiten',
  'Edit date and time': 'Datum und Uhrzeit bearbeiten',
  'Edit duration': 'Dauer bearbeiten',
  'Edit end date': 'Enddatum bearbeiten',
  'Edit end date and time': 'Enddatum und -uhrzeit bearbeiten',
  'Edit end time': 'Endzeit bearbeiten',
  'Edit formal parameters': 'Parameter bearbeiten',
  'Edit function kind': 'Funktionsart bearbeiten',
  'Edit input': 'Eingabe bearbeiten',
  'Edit number': 'Zahl bearbeiten',
  'Edit output': 'Ergebnis bearbeiten',
  'Edit start date': 'Startdatum bearbeiten',
  'Edit start date and time': 'Startdatum und -uhrzeit bearbeiten',
  'Edit start time': 'Startzeit bearbeiten',
  'Edit string': 'Text bearbeiten',
  'Edit time': 'Uhrzeit bearbeiten',
  'Editing not supported for set expression language':
    'Für diese Ausdruckssprache gibt es keinen Editor',
  'Element name': 'Name des Elements',
  'End date': 'Enddatum',
  'End date and time': 'Enddatum und -uhrzeit',
  'End time': 'Endzeit',
  'End value': 'Endwert',
  'Enter expression': 'Ausdruck eingeben',
  Equals: 'Gleich',
  Exactly: 'Genau',
  Exclude: 'Ausschließen',
  Expression: 'Ausdruck',
  'Expression language': 'Ausdruckssprache',
  'Expression language:': 'Ausdruckssprache:',
  'Expression language: {expressionLanguageLabel}': 'Ausdruckssprache: {expressionLanguageLabel}',
  'Function kind: {kind}': 'Funktionsart: {kind}',
  Greater: 'Größer',
  'Greater or equals': 'Größer oder gleich',
  'Hit policy': 'Trefferregel',
  'Hit policy:': 'Trefferregel:',
  Include: 'Einschließen',
  Input: 'Eingabe',
  'Input expression': 'Eingabeausdruck',
  'Input expression: ': 'Eingabeausdruck: ',
  'Input label': 'Bezeichnung der Eingabe',
  'Input label: ': 'Bezeichnung der Eingabe: ',
  'Input type': 'Typ der Eingabe',
  'Input values': 'Zulässige Eingabewerte',
  Kind: 'Art',
  Less: 'Kleiner',
  'Less or equals': 'Kleiner oder gleich',
  'Literal expression': 'Literal-Ausdruck',
  'Literal expression editor': 'Editor für Literal-Ausdrücke',
  'Match none': 'Keinen treffen',
  'Match one': 'Einen treffen',
  'Move rule': 'Regel verschieben',
  No: 'Nein',
  'No values': 'Keine Werte',
  Output: 'Ergebnis',
  'Output label': 'Bezeichnung des Ergebnisses',
  'Output label: ': 'Bezeichnung des Ergebnisses: ',
  'Output name': 'Name des Ergebnisses',
  'Output name: ': 'Name des Ergebnisses: ',
  'Output type': 'Typ des Ergebnisses',
  'Output values': 'Zulässige Ergebniswerte',
  'Paste input column left': 'Eingabespalte links einfügen',
  'Paste input column right': 'Eingabespalte rechts einfügen',
  'Paste output column left': 'Ergebnisspalte links einfügen',
  'Paste output column right': 'Ergebnisspalte rechts einfügen',
  'Paste rule above': 'Regel darüber einfügen',
  'Paste rule below': 'Regel darunter einfügen',
  'Predefined values': 'Vorgegebene Werte',
  Range: 'Bereich',
  'Range end operator': 'Operator am Bereichsende',
  'Range end value': 'Wert am Bereichsende',
  'Range start operator': 'Operator am Bereichsanfang',
  'Range start value': 'Wert am Bereichsanfang',
  'Remove cell description': 'Beschreibung entfernen',
  'Remove input column': 'Eingabespalte entfernen',
  'Remove output column': 'Ergebnisspalte entfernen',
  'Remove parameter': 'Parameter entfernen',
  'Remove rule': 'Regel entfernen',
  Resize: 'Größe ändern',
  'Set date': 'Datum setzen',
  'Set date and time': 'Datum und Uhrzeit setzen',
  'Set duration': 'Dauer setzen',
  'Set time': 'Uhrzeit setzen',
  'Set value': 'Wert setzen',
  'Start date': 'Startdatum',
  'Start date and time': 'Startdatum und -uhrzeit',
  'Start time': 'Startzeit',
  'Start value': 'Startwert',
  'String value': 'Textwert',
  'Strings must be in double quotes': 'Texte stehen in doppelten Anführungszeichen',
  'Test type': 'Art der Prüfung',
  Then: 'Dann',
  Time: 'Uhrzeit',
  'Time value': 'Zeitwert',
  Type: 'Typ',
  'Use now': 'Jetzt verwenden',
  'Use today': 'Heute verwenden',
  Value: 'Wert',
  Values: 'Werte',
  'Variable name': 'Variablenname',
  'Variable name:': 'Variablenname:',
  'Variable type': 'Variablentyp',
  'Variable type:': 'Variablentyp:',
  'View DRD': 'Zur Übersicht',
  When: 'Wenn',
  Yes: 'Ja',
  'e.g. { example } ': 'z. B. { example } ',
  'e.g. { sample }': 'z. B. { sample }',
  name: 'Name',

  // Trefferregeln: dmn-js reicht Bezeichnung und Erklaerung dynamisch durch `translate`.
  // Die DMN-Kennungen (UNIQUE, FIRST, ...) bleiben im XML unveraendert.
  Unique: 'Eindeutig',
  First: 'Erste',
  Priority: 'Priorität',
  Any: 'Beliebig',
  Collect: 'Sammeln',
  'Collect (Sum)': 'Sammeln (Summe)',
  'Collect (Min)': 'Sammeln (Minimum)',
  'Collect (Max)': 'Sammeln (Maximum)',
  'Collect (Count)': 'Sammeln (Anzahl)',
  'Rule order': 'Regelreihenfolge',
  'Output order': 'Ergebnisreihenfolge',
  'No overlap is possible and all rules are disjoint. Only a single rule can be matched':
    'Regeln dürfen sich nicht überschneiden; es trifft höchstens eine Regel.',
  'Rules may overlap. The first matching rule will be chosen':
    'Regeln dürfen sich überschneiden; die erste passende Regel gilt.',
  'Rules may overlap. The one with the highest priority will be chosen':
    'Regeln dürfen sich überschneiden; die mit der höchsten Priorität gilt.',
  'Rules may overlap. Their output have to match':
    'Regeln dürfen sich überschneiden; ihre Ergebnisse müssen übereinstimmen.',
  'Collects the values of all matching rules': 'Sammelt die Ergebnisse aller passenden Regeln.',
  'Collects the values of all matching rules and sums up to a single value':
    'Sammelt die Ergebnisse aller passenden Regeln und summiert sie.',
  'Collects the values of all matching rules and uses the lowest value':
    'Sammelt die Ergebnisse aller passenden Regeln und nimmt den kleinsten Wert.',
  'Collects the values of all matching rules and uses the highest value':
    'Sammelt die Ergebnisse aller passenden Regeln und nimmt den größten Wert.',
  'Collects the values of all matching rules and counts the number of them':
    'Sammelt die Ergebnisse aller passenden Regeln und zählt sie.',
  'Collects the values of all matching rules in rule order':
    'Sammelt die Ergebnisse aller passenden Regeln in Regelreihenfolge.',
  'Collects the values of all matching rules in decreasing output priority order':
    'Sammelt die Ergebnisse aller passenden Regeln nach absteigender Ergebnispriorität.',

  // Fehlermeldungen der Dauer-Eingabe.
  'Must match PnYnM': 'Format PnYnM erwartet, z. B. P1Y2M',
  'Must match PnDTnH': 'Format PnDTnH erwartet, z. B. P2DT3H',

  // Typnamen wie string, number oder date laufen ebenfalls durch `translate`. Sie bleiben
  // bewusst englisch: Es sind die FEEL-Typen, die genau so auch im Ausdruck stehen.
};

/** Übersetzt einen dmn-js-Text und setzt dessen Platzhalter ein. */
export function translateDmn(template: string, replacements: Record<string, unknown> = {}): string {
  const text = GERMAN[template] ?? template;
  return text.replace(/{([^}]+)}/g, (match, key: string) =>
    key in replacements ? String(replacements[key]) : match,
  );
}

/** Das didi-Modul, das dmn-js' eingebauten `translate`-Dienst ersetzt. */
export const germanDmnTranslateModule = {
  translate: ['value', translateDmn],
};

/** Anzahl der übersetzten Texte — für den Test gegen die dmn-js-Fassung. */
export const translatedDmnTexts = Object.keys(GERMAN);
