<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>PostgreSqlStorageSystem</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="Npgsql" Version="10.0.3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Model\Model.csproj" />
        <ProjectReference Include="..\StorageSystemShared\StorageSystemShared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Migrations\*.sql" />
    </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="WebApiEngine.Tests" />
  </ItemGroup>

</Project>
